services:

  web:
    build: .
    container_name: secure-framework-web-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # Set the Apache document root to the /public folder
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    command: >
      bash -c "sed -ri -e 's!/var/www/html!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
      && sed -ri -e 's!/var/www/!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
      && apache2-foreground"

  sqlite-admin:
    image: ghcr.io/coleifer/sqlite-web:latest
    container_name: secure-framework-sqlite-database
    ports:
      - "8081:8080"
    volumes:
      - ./database:/data
    command: secure_app.sqlite
    restart: unless-stopped